Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ubuntu/miniconda3/envs/prepa/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from myst_nb import glue

x = np.linspace(0, np.pi / 2, 1000)
y = np.sin(x) - x ** 3

Kd = 1.1
Kg = 2 - Kd
xd = np.array([np.pi / 4, np.pi / 4 * Kd])
yd = np.sin(xd) - xd ** 3
xg = np.array([np.pi / 4 * Kg, np.pi / 4])
yg = np.sin(xg) - xg ** 3
xc = np.array([np.pi / 4 * Kg, np.pi / 4 * Kd])
xc2 = [np.pi / 4 * Kg, np.pi / 4, np.pi / 4 * Kd]
yc = np.sin(xc) - xc ** 3

f, ax = plt.subplots()
f.suptitle("D√©riv√©e √† droite")
ax.plot(y, x, linewidth=1.3, color="blue")
ax.plot(yd, xd, linewidth=1, color="red")
ax.set_xticks(xd, labels=["x0", "x0+h"])
glue("deriv_d", f, display="False")

f, ax = plt.subplots()
f.suptitle("D√©riv√©e √† gauche")
ax.plot(y, x, linewidth=1.3, color=blue)
ax.plot(yg, xg, linewidth=1, color=red)
ax.set_xticks(xg, labels=["x0-h", "x0"])
glue("deriv_g", f, display="False")

f, ax = plt.subplots()
f.suptitle("D√©riv√©e centr√©e")
ax.plot(y, x, linewidth=1.3, color=blue)
ax.plot(yc, xc, linewidth=1, color=red)
ax.set_xticks(xc2, labels=["x0-h", "x0", "x0+h"])
glue("deriv_c", f, display="False")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-514f8dffbb4f>[0m in [0;36m<module>[0;34m[0m
[1;32m     20[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0my[0m[0;34m,[0m [0mx[0m[0;34m,[0m [0mlinewidth[0m[0;34m=[0m[0;36m1.3[0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m"blue"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     21[0m [0max[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0myd[0m[0;34m,[0m [0mxd[0m[0;34m,[0m [0mlinewidth[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m [0mcolor[0m[0;34m=[0m[0;34m"red"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 22[0;31m [0max[0m[0;34m.[0m[0mset_xticks[0m[0;34m([0m[0mxd[0m[0;34m,[0m [0mlabels[0m[0;34m=[0m[0;34m[[0m[0;34m"x0"[0m[0;34m,[0m [0;34m"x0+h"[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     23[0m [0mglue[0m[0;34m([0m[0;34m"deriv_d"[0m[0;34m,[0m [0mf[0m[0;34m,[0m [0mdisplay[0m[0;34m=[0m[0;34m"False"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     24[0m [0;34m[0m[0m

[0;32m~/miniconda3/envs/prepa/lib/python3.9/site-packages/matplotlib/axes/_base.py[0m in [0;36mwrapper[0;34m(self, *args, **kwargs)[0m
[1;32m     61[0m [0;34m[0m[0m
[1;32m     62[0m         [0;32mdef[0m [0mwrapper[0m[0;34m([0m[0mself[0m[0;34m,[0m [0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 63[0;31m             [0;32mreturn[0m [0mget_method[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     64[0m [0;34m[0m[0m
[1;32m     65[0m         [0mwrapper[0m[0;34m.[0m[0m__module__[0m [0;34m=[0m [0mowner[0m[0;34m.[0m[0m__module__[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/envs/prepa/lib/python3.9/site-packages/matplotlib/cbook/deprecation.py[0m in [0;36mwrapper[0;34m(*args, **kwargs)[0m
[1;32m    449[0m                 [0;34m"parameter will become keyword-only %(removal)s."[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m    450[0m                 name=name, obj_type=f"parameter of {func.__name__}()")
[0;32m--> 451[0;31m         [0;32mreturn[0m [0mfunc[0m[0;34m([0m[0;34m*[0m[0margs[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    452[0m [0;34m[0m[0m
[1;32m    453[0m     [0;32mreturn[0m [0mwrapper[0m[0;34m[0m[0;34m[0m[0m

[0;31mTypeError[0m: set_ticks() got an unexpected keyword argument 'labels'
TypeError: set_ticks() got an unexpected keyword argument 'labels'

