Traceback (most recent call last):
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "D:\cedri\anaconda3\envs\prepa\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "D:\cedri\anaconda3\envs\prepa\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
xf1 = dicho_while(f, -2, 0, 1e-12)
xf2 = dicho_recursif(f, -2, 0, 1e-12)
xf3 = bisect(f, -2, 0)

xg1 = dicho_while(g, 0, np.pi, 1e-12)
xg2 = dicho_recursif(g, 0, np.pi, 1e-12)
xg3 = bisect(g, 0, np.pi)

xh1 = dicho_while(h, 0.1, 1, 1e-12)
xh2 = dicho_recursif(h, 0.1, 1, 1e-12)
xh3 = bisect(h, 0.1, 1)

print("Racine de f : {}".format([xf1, xf2, xf3]))
print("Racine de g : {}".format([xg1, xg2, xg3]))
print("Racine de h : {}".format([xh1, xh2, xh3]))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn [4], line 2[0m
[0;32m      1[0m xf1 [38;5;241m=[39m dicho_while(f, [38;5;241m-[39m[38;5;241m2[39m, [38;5;241m0[39m, [38;5;241m1e-12[39m)
[1;32m----> 2[0m xf2 [38;5;241m=[39m [43mdicho_recursif[49m[43m([49m[43mf[49m[43m,[49m[43m [49m[38;5;241;43m-[39;49m[38;5;241;43m2[39;49m[43m,[49m[43m [49m[38;5;241;43m0[39;49m[43m,[49m[43m [49m[38;5;241;43m1e-12[39;49m[43m)[49m
[0;32m      3[0m xf3 [38;5;241m=[39m bisect(f, [38;5;241m-[39m[38;5;241m2[39m, [38;5;241m0[39m)
[0;32m      5[0m xg1 [38;5;241m=[39m dicho_while(g, [38;5;241m0[39m, np[38;5;241m.[39mpi, [38;5;241m1e-12[39m)

Cell [1;32mIn [2], line 14[0m, in [0;36mdicho_recursif[1;34m(f, a0, b0, prec)[0m
[0;32m     12[0m [38;5;28;01mif[39;00m f(c) [38;5;241m==[39m [38;5;241m0[39m:
[0;32m     13[0m     [38;5;28;01mreturn[39;00m c
[1;32m---> 14[0m [38;5;28;01melif[39;00m f(c) [38;5;241m*[39m f([43mb[49m) [38;5;241m<[39m [38;5;241m0[39m:
[0;32m     15[0m     [38;5;28;01mreturn[39;00m dicho_recursif(f, c, b, prec)
[0;32m     16[0m [38;5;28;01melse[39;00m:

[1;31mNameError[0m: name 'b' is not defined
NameError: name 'b' is not defined

